### ISSUE TITLE
item move bug

### ISSUE THREAD

**Issue by yanyiheng13** [cundong/HeaderAndFooterRecyclerView#1]
例子不错，不知道大神发现例子中瀑布流存在一个问题，还是没法用到实际项目中去：
    瀑布流加载下一页成功后再返回到顶部，会明显的看到item移动。有解决办法吗？

**Comment by yanyiheng13** [comment]
楼主，问题已经解决，在加载下一页的时候调用 notifyItemRangeInserted(startPostion, itemCount)  而不是 notifyDataSetChanged()，这样在加载下一页的时候，下一页计算GAP的同时不会影响上一页的gap，个人观点

**Comment by cundong** [comment]
好的~ 你发起一个pullRequest吧，我合并一下代码。谢谢了。

**Comment by cundong** [comment]
Done
