### ISSUE TITLE
很不错，希望能交流下。

### ISSUE THREAD

**Issue by kaleai** [cundong/HeaderAndFooterRecyclerView#3]
我 460412008@qq.com

**Comment by kaleai** [comment]
HeaderAndFooterRecyclerViewAdapter 中放入setAdapter不太合适，设置跨列的代码或许有点性能问题。

**Comment by cundong** [comment]
@tianzhijiexian 怎么可能有性能问题呢，HeaderAndFooterRecyclerViewAdapter 中放入setAdapter，其实内部实现还是将这个Adapter设置给了innerAdapter，和我们普通的用法是一样的啊。

**Comment by kaleai** [comment]
是我理解出现了偏差
