### ISSUE TITLE
EndlessLinearLayoutActivity 横向加载有问题。

### ISSUE THREAD

**Issue by jiaowenzheng** [cundong/HeaderAndFooterRecyclerView#36]
LinearLayoutManager lm = new LinearLayoutManager(this);
        lm.setOrientation(LinearLayoutManager.HORIZONTAL);
        mRecyclerView.setLayoutManager(lm);

如果设置为横向 ，中能加载一页数据。

**Comment by cundong** [comment]
目前只是支持竖直的。
