### ISSUE TITLE
【功能建议】是否考虑添加首次无内容跟网络错误的view

### ISSUE THREAD

**Issue by NicodeLee** [cundong/HeaderAndFooterRecyclerView#4]
加上这个解决方案就更加完整了。

**Comment by cundong** [comment]
@NicodeLee 你的建议挺好。
但是我觉得要是加上之后这个库就有点太冗杂了，所以就没有加。

**Comment by NicodeLee** [comment]
最近也思考了一下，做得越少，做的越好。越容易使用、传播、分享。为你当初的坚持点赞。

**Comment by cundong** [comment]
@NicodeLee 谢谢你啊~ 多给这个项目提交patch啊~
