### ISSUE TITLE
莫名其妙发生IllegalArgumentException

### ISSUE THREAD

**Issue by LiuJQ** [cundong/HeaderAndFooterRecyclerView#7]
java.lang.IllegalArgumentException: Called attach on a child which is not detached: ViewHolder

**Comment by cundong** [comment]
能找到复现场景或者堆栈信息吗？

**Comment by LiuJQ** [comment]
感谢关注，我发现了问题所在，并不是作者的代码错误。
导致上述问题的原因是，我在更新了RecyclerView的数据集后，调用了notifyItemRangeChanged(original_last, original_last + data.size());更新，然而后来发现是多此一举并且导致了IllegalArgumentException。

以前一直使用ListView绑定Adapter，更新了数据集后都需要notifyDataSetChanged()刷新一下，而现在发现RecyclerView并不需要，第一次使用RecyclerView，见笑了。
